containers/kubernetes-mcp-server

README.md
pkg/kubernetes/pods.go
pkg/mcp/pods.go
pkg/mcp/pods_exec_test.go

Fixes #56
Allows to specify the container where the command will be executed. Additionally, prevents the command from failing in pods with multiple containers when the container is not specified (defaults to first).

feat(pods): pods_exec supports specifying container

---

pkg/kubernetes/configuration.go

fix: use KUBECONFIG or explicitly given kubeconfig file (#67)

---

pkg/kubernetes/kubernetes.go
pkg/mcp/mcp.go
pkg/mcp/mcp_test.go

Relates to https://github.com/openshift/lightspeed-service/pull/2536

feat(auth)!: use generic kubernetes-authorization header

---

pkg/mcp/mcp_test.go

Darwin (macOS) isn't a linux platform.

Fix typo in test skip message for non-Unix-like platforms

---

pkg/mcp/namespaces_test.go
pkg/mcp/pods_test.go
pkg/mcp/resources_test.go

test(output): additional tests for --list-output=table

---

pkg/mcp/configuration.go
pkg/mcp/events.go
pkg/mcp/helm.go
pkg/mcp/mcp.go
pkg/mcp/namespaces.go
pkg/mcp/pods.go
pkg/mcp/profiles.go
pkg/mcp/resources.go
pkg/output/output.go

Trivial changes to use `ptr.Deref` and reorganizing go imports.

Use built-in ptr.Deref instead of a custom func

---

go.mod
pkg/config/config.go
pkg/config/config_test.go
pkg/kubernetes-mcp-server/cmd/root.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/resources.go
pkg/mcp/common_test.go
pkg/mcp/mcp.go
pkg/mcp/mcp_test.go
pkg/mcp/resources_test.go
pkg/output/output.go

Fixes #131 
Introduces PoC for #132 
This PR introduces a new static configuration file in toml format that defaults to `conf.toml` but can be modified via flag `config`. 
Additionally, this PR adds predefined set of resources to not allow any operations in MCP Server.
This PR is supposed to fix https://github.com/manusa/kubernetes-mcp-server/issues/132 and https://github.com/manusa/kubernetes-mcp-server/issues/131

Introduce toml configuration file with a set of deny list

---

pkg/mcp/resources.go

I noticed the panic while testing due to the unexpected types of objects. This PR checks the type first and returns error gracefully to prevent panic (which results in the crash of application)

Gracefully cast objects and return err instead of panic

---

.gitignore
pkg/config/config.go
pkg/config/config_test.go
pkg/kubernetes-mcp-server/cmd/root.go
pkg/kubernetes-mcp-server/cmd/root_test.go
pkg/kubernetes-mcp-server/cmd/testdata/valid-config.toml

This PR adds support of passing flag values in configurations files as described in https://github.com/manusa/kubernetes-mcp-server/issues/137. Flags are always higher priority than the configuration definitions.
This PR fixes https://github.com/manusa/kubernetes-mcp-server/issues/137

Define flags in configuration file

---

pkg/kubernetes/accesscontrol.go
pkg/kubernetes/accesscontrol_clientset.go
pkg/kubernetes/accesscontrol_restmapper.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/pods.go
pkg/kubernetes/resources.go
pkg/mcp/events_test.go
pkg/mcp/helm_test.go
pkg/mcp/namespaces_test.go
pkg/mcp/pods_exec_test.go
pkg/mcp/pods_test.go
pkg/mcp/pods_top_test.go
pkg/mcp/resources_test.go

Fixes #132
This approach ensures that resources in the deny list are **always** processed regardless of the implementation.
The RESTMapper takes care of verifying that the requested Group Version Kind complies with the deny list while checking for the REST endpoint.
/cc @ardaguclu

feat(config): deny resources by using RESTMapper as an interceptor

---

pkg/config/config.go
pkg/config/config_test.go
pkg/kubernetes-mcp-server/cmd/root.go
pkg/kubernetes-mcp-server/cmd/testdata/valid-config.toml
pkg/mcp/common_test.go
pkg/mcp/mcp.go
pkg/mcp/mcp_test.go

Fixes #156 
This PR introduces enabled/disabled tool list in the configuration file. 
Users will be able to add enabled and disabled tools in the configuration file. e.g.
```toml
enabled_tools = ["configuration_view", "events_list", "namespaces_list", "pods_list", "resources_list", "resources_get", "resources_create_or_update", "resources_delete"]
disabled_tools = ["pods_delete", "pods_top", "pods_log", "pods_run", "pods_exec"]
```
This list will be applied to the given profile (full is the default);
* If enabled list is empty, all the tools given in the profile will be populated
* If enabled list is not empty, only the enabled tools will be populated
* If disabled list is not empty, specifically disabled tools will be removed from the tool list.
This PR partially fixes …

Introduce enabled/disabled tool list in configuration file

---

pkg/http/http.go
pkg/kubernetes-mcp-server/cmd/root.go
pkg/mcp/mcp.go
pkg/middleware/middleware.go

This PR is the continuation of https://github.com/manusa/kubernetes-mcp-server/pull/153. First commit basically is from https://github.com/manusa/kubernetes-mcp-server/pull/153. Second commit introduces the middleware.
This middleware;
* logs requests if the log-level is 5 or higher
* will check the authorization header and return accordingly, if bearer token is not found.

Introduce middleware for audit logs and authentication checks

---

pkg/kubernetes/configuration.go
pkg/kubernetes/configuration_test.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/kubernetes_test.go
pkg/mcp/mcp.go

As promised in https://github.com/manusa/kubernetes-mcp-server/pull/163#issuecomment-3043492636, this PR adds unit tests to increase the test coverage of Derived Config. Derived Config is crucial piece in the flow. So that we need to ensure that it's values are correctly set.
Additionally, this PR removes redundant kubeconfig field in Manager. We already have kubeconfig in StaticConfig and we pass StaticConfig to every place. Therefore, there is no need to maintain another field that must actually be equal to staticConfig.kubeconfig.

Add new test case to increase the test coverage of Derived Config

---

go.mod
go.sum
pkg/http/authorization.go
pkg/http/authorization_test.go
pkg/http/http.go
pkg/kubernetes-mcp-server/cmd/root.go
pkg/kubernetes-mcp-server/cmd/root_test.go
pkg/mcp/mcp.go

This PR is revamped version of https://github.com/manusa/kubernetes-mcp-server/pull/172.
If Authorization URL is set, that means MCP Server is asked to validate the tokens from the given issuer url.
This PR adds support this. Currently, the expectation is to get one token regardless of the authorization url is specified or not. And this token is used against API Server after validated.

Introduce OIDC token verification if authorization-url is specified

---

pkg/http/http_test.go

Contains tests for the main endpoints (proxied and handled)
- /sse
- /message
- /mcp
- /healthz
- /.well-known/oauth-protected-resource
Verifies graceful shutdown works as expected

test(http): bootstrap tests for HTTP server

---

Makefile
pkg/helm/helm.go
pkg/kubernetes-mcp-server/cmd/root.go
pkg/kubernetes/configuration.go
pkg/kubernetes/impersonate_roundtripper.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/kubernetes_test.go
pkg/mcp/common_test.go
pkg/mcp/configuration.go
pkg/mcp/events.go
pkg/mcp/helm.go
pkg/mcp/mcp.go
pkg/mcp/mcp_test.go
pkg/mcp/pods.go
pkg/mcp/pods_test.go
pkg/mcp/pods_top_test.go
pkg/mcp/resources.go
pkg/mcp/resources_test.go

fix(lint): add golangci-lint make target + lint

---

pkg/http/authorization.go
pkg/http/authorization_test.go
pkg/http/http_test.go

Relates to:
- #189 
- #179 
- https://github.com/containers/kubernetes-mcp-server/pull/176#discussion_r2210288722
/cc @ardaguclu

test(auth): complete test suite for unauthorized scenarios

---

AGENTS.md

Fixes #205
To better enable code agents to work with this repo, add an AGENTS.md that describes the project from a code perspective for an agent.

chore(doc): add AGENTS.md

---

npm/kubernetes-mcp-server/bin/index.js
pkg/http/http.go

fix(npm): child process exits gracefully on SIGxxx

---

pkg/mcp/mcp.go

It's unclear how the scopes are going to be populated in the JWT. Disable scope authorization for the time being.
/cc @ardaguclu

refactor(auth): temporarily disable scope authorization

---

pkg/config/config.go
pkg/http/authorization.go
pkg/http/http_test.go
pkg/http/wellknown.go

Adds `DisableDynamicClientRegistration` and `OAuthScopes` to be able to override the values proxied from the configured authorization server.
DisableDynamicClientRegistration removes the registration_endpoint field from the well-known authorization resource metadata.
This forces VSCode to show a for to input the Client ID and Client Secret since these can't be discovered.
The OAuthScopes allows to override the scopes_supported field. VSCode automatically makes an auth request for all of the supported scopes.
In many cases, this is not supported by the auth server. By providing this configuration, the user (MCP Server administrator) is able to set which scopes are effectively supported and force VSCode to only request these.

feat(auth): support for VSCode auth flow

---

pkg/http/http_test.go
pkg/kubernetes/common_test.go
pkg/mcp/common_test.go
pkg/mcp/configuration_test.go

Supersedes closes #280
Closes https://github.com/openshift/openshift-mcp-server/pull/26
Fixes #273 
Test set up processes are incomplete and don't override all of the deteted environment settings.
This PR ensures that the tests run on any environment under the same conditions.
/cc @ardaguclu

fix:test: prevent usage of real cluster in tests

---

pkg/mcp/helm_test.go
pkg/mcp/mcp_tools_test.go
pkg/mcp/namespaces_test.go
pkg/mcp/pods_exec_test.go
pkg/mcp/pods_test.go
pkg/mcp/profiles_test.go

test: misc fixes and typos

---

go.mod
pkg/kubernetes-mcp-server/cmd/root.go
pkg/kubernetes-mcp-server/cmd/root_test.go

Prevents protocol issues with some clients.
Kubernetes tooling uses klog to log messages.
Some of these messages end up logged in the stderr or stdout which breaks some of the clients that expect jsonrpc messages.
/cc @ardaguclu

fix(cmd): disable klog in STDIO mode

---

README.md
pkg/kubernetes/pods.go
pkg/mcp/pods_test.go
pkg/mcp/testdata/toolsets-core-tools.json
pkg/mcp/testdata/toolsets-full-tools-openshift.json
pkg/mcp/testdata/toolsets-full-tools.json
pkg/toolsets/core/pods.go

feat(pods): add optional tail parameter to pod logs retrieval

---

pkg/mcp/events_test.go
pkg/toolsets/core/events.go

feat(mcp): events_list returns parseable YAML output

---

pkg/config/config.go
pkg/kubernetes-mcp-server/cmd/root.go
pkg/kubernetes-mcp-server/cmd/root_test.go
pkg/kubernetes/provider.go

This PR builds on top of #348 to allow for a "disabled" strategy, as well as a command line flag for disabling the multi cluster support.
To disable multi-cluster, users can start the server with:
```bash
./kubernetes-mcp-server --port 8080 --disable-multi-cluster
```
Relates to #83

feat: add "disabled" mutli cluster strategy
